-- Corrige el tope del "Offset posición recogida" del Divisor (BS08)
-- en ceria_documentacion_maquina -- sesión 13/09/2026.
--
-- Aclaración del encargado: 0-3 mm era el RANGO HABITUAL observado,
-- no un tope técnico real. El parámetro no tiene límite superior
-- definido. Criterio operativo (pensado para que lo use personal
-- sin formación técnica, sin complicarles la decisión):
--   - Si hace falta dividir más abajo (sobra pieza), simplemente
--     subir el offset -- no hay que preocuparse por ningún límite.
--   - Si se supera 8 mm, se puede seguir operando así sin ningún
--     problema ni urgencia -- pero es una señal de que "Intereje
--     FT/mordaza" u "Offset calibr." pueden estar desajustados de
--     fondo, y conviene avisar al mecánico para que lo revise
--     cuando pueda (no es un aviso urgente ni bloqueante).
--
-- Filas afectadas:
--   1) bs08.divisor.parametro.offset_posicion_recogida -- quita el
--      "0-3 mm" como límite, lo deja como referencia orientativa;
--      añade el criterio de aviso a partir de 8 mm.
--   2) bs08.divisor.diagnostico.divide_mal -- la rama "sobra pieza"
--      ya no dice "si el offset está al límite (0-3mm)"; ahora dice
--      "si hace falta subir de 8 mm, avisar al mecánico sin urgencia".
--   3) bs08.divisor.parametro.intereje_ft_mordaza -- quita el "(0-3
--      mm)" y "al límite" del apartado que compara con el offset;
--      lo deja consistente con que el offset no tiene tope.

update ceria_documentacion_maquina set
  contenido = 'Corrige la posición calculada para la división, permitiendo realizarla solo más abajo de la calculada — a más valor, más abajo. No admite valores negativos (no se puede corregir hacia arriba). No tiene un tope técnico definido, se puede aumentar sin problema; el "rango habitual" (0-3 mm) es solo orientativo, no un límite real. Valor capturado: 1 mm. Se reajusta por formato. Actúa directamente sobre la cota de corte (1 mm de offset = 1 mm de corte), a diferencia del error de intereje, que llega al corte dividido por el número de divisiones. Guía para el operario: si hace falta dividir más abajo (sobra pieza en la caja), simplemente subir este valor, sin más complicación. Si en algún momento hay que superar los 8 mm, se puede seguir así sin problema — no hay ningún riesgo inmediato —, pero es una señal de que "Intereje FT/mordaza" u "Offset calibr." pueden estar desajustados de fondo: avisar al mecánico para que lo revise cuando pueda, sin urgencia. Diagnóstico: si la caja llega con MÁS piezas de las que le tocan (o "se escapa una pieza" hacia esa caja) — puede pasar en cualquier división del ciclo, no en una posición fija —, es síntoma de que el divisor está dividiendo demasiado arriba: este es el ajuste habitual y más sencillo para corregirlo. Si en cambio falta alguna pieza, este offset no puede corregirlo bajo ningún concepto (no admite ir hacia arriba): ver directamente "Intereje FT/mordaza".',
  updated_at = now()
where clave = 'bs08.divisor.parametro.offset_posicion_recogida';

update ceria_documentacion_maquina set
  contenido = 'Paso 0 — descartar mecánica antes que parámetro: si el fallo es errático (a veces sobra, a veces falta, sin patrón claro, y/o va acompañado de piezas rotas o ruido), sospechar fallo mecánico, no paramétrico — ver "bs08.divisor.mantenimiento.criterio_mecanico_vs_parametro" y las pruebas de juego/balanceo. Solo seguir con lo siguiente si el fallo tiene una dirección CONSISTENTE (siempre sobra, o siempre falta pieza) — puede aparecer en cualquier división del ciclo, de forma no siempre predecible (el margen de corte es muy ajustado, y una pieza puede escaparse o quedarse pillada en cualquier corte); lo relevante no es EN QUÉ división pasa, sino en qué DIRECCIÓN falla siempre. Pregunta clave: cuando falla, ¿la caja sale con una pieza DE MÁS, o con una pieza DE MENOS? → Si SOBRA pieza (el divisor está dividiendo demasiado arriba): subir "Offset posición recogida" — no tiene tope definido, se puede subir sin problema hasta que se corrija. Comprobar también el desgaste de la parte baja de la mordaza vulcanizada (ver "bs08.divisor.pieza.mordaza_vulcanizada"): una mordaza desgastada divide más arriba y da exactamente este síntoma; si el desgaste es grande, sustituirla en vez de seguir compensando con offset. Si hace falta subir el offset por encima de 8 mm para corregirlo, se puede seguir operando así sin problema, pero es señal de que "Intereje FT/mordaza" u "Offset calibr." pueden estar desajustados de fondo: avisar al mecánico para que lo revise cuando pueda, sin urgencia (ver "bs08.divisor.mantenimiento.verificacion_intereje_ft_mordaza"). → Si FALTA pieza (el divisor está dividiendo demasiado abajo): "Offset posición recogida" NO puede corregir esto bajo ningún concepto, porque solo admite corregir hacia abajo, nunca hacia arriba — hay que revisar y corregir directamente "Intereje FT/mordaza". Antes, comprobar que el operario no ha dejado "Offset posición recogida" alto de un formato anterior. Recordar que la cota de corte = altura medida ÷ número de divisiones: el error de intereje llega al corte dividido por ese número.',
  updated_at = now()
where clave = 'bs08.divisor.diagnostico.divide_mal';

update ceria_documentacion_maquina set
  contenido = 'Altura de la fotocélula de medición (sobre las mordazas) respecto a la parte baja de la mordaza — es la fotocélula que mide la altura de la pila para calcular las divisiones. Valor capturado: 68 mm. Dato constructivo/físico: NO se reajusta como parte de un cambio de formato rutinario. Solo cambia si se manipula físicamente la posición de la fotocélula — por accidente (golpe, deformación) o, más raramente, de forma deliberada, cuando un formato nuevo trae una pila cuya altura real queda fuera del rango medible con el montaje actual. Relación derivada: como la mordaza nunca baja por debajo de su posición de calibrado (el cero, que queda 1-2 mm por encima de las cadenas — ver "Offset calibr.") y la fotocélula va siempre a esta distancia por encima de la mordaza, este valor es la altura MÍNIMA de pila medible por fotocélula. Ver "Posición espera" para el límite superior del rango, y la alarma "TO lectura altura pila" para el síntoma cuando la pila cae fuera de rango. Para formatos con pila más baja que este valor (p. ej. 120x120 de 4 piezas) se trabaja con "División de la pila sin fotocélula" y cota fija, no se mueve la fotocélula. Diagnóstico adicional: si el intereje programado está por DEBAJO del real (la fotocélula física está, en realidad, más arriba de lo programado), la máquina SUBESTIMA la altura de la pila y calcula cada corte más abajo de lo que toca — el divisor divide demasiado abajo, con riesgo de que FALTE alguna pieza en cualquier caja del ciclo (nunca se corrige con "Offset posición recogida", que solo permite ir hacia abajo). Si el intereje programado está por ENCIMA del real (la fotocélula física está, en realidad, más abajo de lo programado), la máquina SOBREESTIMA la altura de la pila y calcula cada corte más arriba de lo que toca — el divisor divide demasiado arriba, con riesgo de que SOBRE alguna pieza en cualquier caja del ciclo; si el desajuste es pequeño, se puede compensar simplemente subiendo el "Offset posición recogida" (que no tiene tope definido); si el offset necesario para compensarlo supera los 8 mm, es más indicado corregir el intereje directamente en vez de seguir subiendo el offset — aunque seguir subiéndolo seguiría funcionando mientras tanto. Magnitud del efecto: el error de intereje entra entero en la altura medida, pero la cota de corte es altura ÷ "Número de divisiones por pila", así que al corte solo llega dividido por el número de divisiones (20 mm de error de intereje con 5 divisiones = 4 mm de error en el corte). A diferencia del "Offset posición recogida", que mueve el corte 1 mm por cada mm. En ambos casos el fallo puede aparecer en cualquier división del ciclo, no en una posición fija — lo que distingue la causa es la DIRECCIÓN del error (sobra/falta), no en qué caja concreta ocurre. Ver "bs08.divisor.mantenimiento.verificacion_intereje_ft_mordaza" para el procedimiento de verificación y corrección.',
  updated_at = now()
where clave = 'bs08.divisor.parametro.intereje_ft_mordaza';
